# check what is installed in ubuntu-latest https://github.com/actions/virtual-environments
name: Build CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_HOME:   ${ANDROID_HOME}
      ANDROID_SDK:        ${ANDROID_HOME}
      ANDROID_NDK_HOME:   ${ANDROID_NDK_LATEST_HOME}
      ANDROID_NDK:        ${ANDROID_NDK_LATEST_HOME}
    steps:
    - name: install packages
      run: |
        sudo apt-get update || sudo apt-get update
        sudo apt-get install -y ninja-build maven build-essential wget curl unzip git pkg-config
    - name: install recent nasm for dav1d
      run: |
        wget http://ftp.debian.org/debian/pool/main/n/nasm/nasm_2.15.05-1_amd64.deb
        sudo dpkg -i ./nasm_2.15.05-1_amd64.deb
        nasm --version
    - name: install compatible meson with dav1d
      run: |
        sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel
        sudo pip3 install meson==0.53.2
        meson --version
    - name: install repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/local/bin/repo > /dev/null
        sudo chmod a+x /usr/local/bin/repo
    - name: retrieve full nova source
      run: |
         mkdir nova
         cd nova
         repo init -u https://github.com/nova-video-player/aos-AVP -b nova -m v6_1.xml
         repo sync -j 4
         repo forall -c 'git checkout -t $REPO_REMOTE/$REPO_RREV'
         
    - name: create keystore and properties file for signing the app   
      run: |
        echo "storeFile=/home/runner/work/_temp/keystore/test.jks" >> /home/runner/work/aos-AVP/aos-AVP/nova/Video/keystore.properties
        echo "keyAlias=$SIGNING_KEY_ALIAS" >> /home/runner/work/aos-AVP/aos-AVP/nova/Video/keystore.properties
        echo "storePassword=$SIGNING_STORE_PASSWORD" >> /home/runner/work/aos-AVP/aos-AVP/nova/Video/keystore.properties
        echo "keyPassword=$SIGNING_KEY_PASSWORD" >> /home/runner/work/aos-AVP/aos-AVP/nova/Video/keystore.properties

    - name: build
      run: |
        cd nova/Video
        ./gradlew aNR
    - uses: actions/upload-artifact@v3
      with:
        name: update
        path: /home/runner/work/aos-AVP/aos-AVP/nova/Video/build/outputs/apk/noamazon/release/